### ISSUE TITLE
Robot Connection Failed Problem

### ISSUE THREAD

**Issue by chenhaox** [hsinkoyu/fs100#1]
Dear author,

When I tried to connect to the FS100 Controller, we confront an error "ConnectionError: timed out". I have already set the " #82015 CMD REMOTE SEL" on and set the controller to remote mode.
So I would like to ask what setting have you made on the FS100 Pendant before you connect.

Thank you for your time and may you have a nice day.

**Comment by hsinkoyu** [comment]
There are other undocumented settings needed to be set by vendor on pendant.
Please ask vendor for the support of HSE. Thanks.
