### ISSUE TITLE
Write I/O does not work

### ISSUE THREAD

**Issue by alexlt97** [hsinkoyu/fs100#10]
Hi I am trying to write an I/O from the fs100 code. 

I am activating the output signal port=3002, when I send the command I received the error:
failed writing the variable, err=0xa001

Checking the error it seems an Instance error, however the rest of the variables works with the instance=1

Any idea what is the issue? Do I need to change the configuration of the robot to allow the writting of I/O?

Kind regards,
Alejandro

**Comment by hsinkoyu** [comment]
Please see #2. 
I don't know there exists a robot configuration for allowing writing of I/O other than network input.

Thanks,
Hsinko
