### ISSUE TITLE
Read_torque function units output

### ISSUE THREAD

**Issue by alexlt97** [hsinkoyu/fs100#11]
Good morning,

First thank you for your work! 
I am currently testing the function read_torque, however I did not find neither here or in the fs100 HIGH-SPEED ETHERNET SERVER documentation what are the unit of the function output. While testing I received positive and negatives values so I assume it cannot be % of power if yes, maybe the decoding is incorrect?

Do you have any idea?

**Comment by hsinkoyu** [comment]
Hi,

We can monitor the torque value change from the pendant.
See section 8.9 Servo Monitoring of [FS100 Maintenance](https://www.motoman.com/getmedia/400b12ad-3a38-47f7-b438-64350d860b92/159645-1CD.pdf.aspx).
Then servo on and force the axis to see the value change.
Positive and negative values explain the direction you force to the axis.
About the unit of torque, according to the [Specification](https://www.motoman.com/en-us/products/robots/industrial/assembly-handling/sia-series/sia10f), it should be Newton-meters (Nm).

Thanks,
Hsinko

**Comment by alexlt97** [comment]
Again thank you for your support!
