### ISSUE TITLE
Read/Write bit on IO variable

### ISSUE THREAD

**Issue by ruisebastiao** [hsinkoyu/fs100#2]
Hello,

is it possible to read/write  a variable of IO type, addressing only a single bit?
Thanks

**Comment by hsinkoyu** [comment]
Hi,

To read/write an IO variable is supported. For addressing a single bit of an IO, just
bitwise the bit after reading and before writing the variable. But note that only 
'network input' IO (2501-2628 for FS100 ) are writable (see p.49 of spec.) for HSE or
you would get 'Instance error (0xa001) when writing.
An alternative way to write IO that are read only for HSE is to have a job doing 
writing thing on Pendant and then play the job by HSE.
Thanks.

**Comment by ruisebastiao** [comment]
Thank you for the help!
