### ISSUE TITLE
read_position in a higher sampling rate

### ISSUE THREAD

**Issue by chungshan** [hsinkoyu/fs100#4]
I'm using ```read_position``` to read robot's pose
https://github.com/hsinkoyu/fs100/blob/master/fs100.py#L1258-L1264
I find that its sampling rate is around 50Hz.
Is it possible to increase this sampling rate of robot's pose?

**Comment by hsinkoyu** [comment]
Hi,

As you said the duration of read_position() is about 20ms, but you will find the
response from controller almost takes the all time. Maybe you can ask Yaskawa for advise.

read_position():                     len(data)=1000, min=0.01480412483215332, max=0.021013975143432617, mean=0.019992566108703612
Receive from controller(recvfrom()): len(data)=1000, min=0.01466059684753418, max=0.020888328552246094, mean=0.019819601535797118

Thanks.
