### ISSUE TITLE
Moving robot using absolute pulse values

### ISSUE THREAD

**Issue by MKhedr133** [hsinkoyu/fs100#5]
After checking the FS100 code and datasheet. It is a bit unclear on how to move the robot using absolute pulse values. For example: home pose robot independent from adjusted robot tool in the pendant.

**Comment by hsinkoyu** [comment]
Hi,

Are you referring to this command?
'3.3.40 Move Instruction Command (Type Pulse)'
I did not implement code for this. I will consider doing it.
By the way, what command do you use to get the destination pulse value?

Thanks,
Hsinko

**Comment by MKhedr133** [comment]
> Hi,
> 
> Are you referring to this command? '3.3.40 Move Instruction Command (Type Pulse)' I did not implement code for this. I will consider doing it. By the way, what command do you use to get the destination pulse value?
> 
> Thanks, Hsinko

Yes, that is the command that I was referring to. For now i use Cartesian coordinates to go to desired poses. 
I referred to 3.3.39 Move instruction command (Type Cartesian coordinates) to get the right format for the coordinates.


Best regards, Mohamed

**Comment by hsinkoyu** [comment]
Hi,

fs100.py module is now to support pulse move.
[https://github.com/hsinkoyu/fs100/blob/master/fs100.py#L1309-L1316](https://github.com/hsinkoyu/fs100/blob/master/fs100.py#L1309-L1316)

Thanks,
Hsinko

**Comment by MKhedr133** [comment]
Thanks, this works fine. However, i faced a new problem when trying to read the current pulse values using read_position() and adjusting the robot_no to 1,2,11,12. I referred to 3.3.6 Robot Position Data Reading Command.

**Comment by hsinkoyu** [comment]
Hi,

What error number did you get?
You could see the error log like this:
failed reading the position info, err=0x??

Thanks,
Hsinko

**Comment by MKhedr133** [comment]
When putting robot_no to 1, it gives this error: 'struct.error: unpack requires a buffer of 4 bytes' .
When putting robot_no to 2/11/12/21/22/23, it gives 'failed reading the position info, err=0xa001'. Which in the datasheet it says that it is an instance error.

After analyzing the error, the problem was solved by removing struct.unpack('<i', ans.data[44:48])[0] from read_position() and appending it if robot_no = 101; by converting the tuple to a list then to a tuple again.

**Comment by hsinkoyu** [comment]
Hi,

Thanks for the info.
For the instance error, I think they are reasonable.
For the 'struct.error' exception, since our robot has no problem with read_position(), I
think the returned packet length is dependent on number of robot axis. I will commit
code like this for read_position():
`p = list()`
`for n in range(20, len(ans.data), 4):`
`    p.append(struct.unpack('<i', ans.data[n:n+4])[0])`
`pos_info['pos'] = tuple(p)`

Thanks,
Hsinko
