### ISSUE TITLE
Moving the robot in a straigt line 

### ISSUE THREAD

**Issue by MKhedr133** [hsinkoyu/fs100#6]
I was trying to move the robot in a straight line instead of an arc; more like moveL in its pendant. I browsed the FS100 datasheet to find Straight absolute position operation as a movement type. I could not find any explanation on this move type. Can you illustrate it please? I tried using this move type, but the movement was not  as expected; either not moving at all and giving an error or going to another pose far from the given pose.

**Comment by hsinkoyu** [comment]
Hi,
Please use FS100.MOVE_TYPE_LINEAR_ABSOLUTE_POS as move_type argument for mov() function.
Ex.
`robot.mov(FS100.MOVE_TYPE_LINEAR_ABSOLUTE_POS, FS100.MOVE_COORDINATE_SYSTEM_ROBOT, FS100.MOVE_SPEED_CLASS_MILLIMETER, 1000, target_pos)`

Thanks,
Hsinko
